#
# BASE CONFIGURATION
#

# `base_url` should only be changed if your site isn't hosted at the root of a domain.
# `domain` is used to generate absolute URLs. (required to generate a valid feed)
#
#   Example:
#       http://my-site.com/
#           base_url: /
#           domain: my-site.com
#       http://my-site.com/my-blog/
#           base_url: /my-blog/
#           domain: my-site.com
base_url: /
domain: projectmusiced.xyz


#
# METADATA
#

# Used in header meta tags and the site feed. (required to generate a valid feed)
author: Austin Clark
# A description of your site to be used in header meta tags.
description: the ramblings of a geeky music educator
# Used in the site feed.
email: clarka94@gmail.com
# Your site's subtitle.
subtitle: the ramblings of a geeky music educator
# Your site's title. (required to generate a valid feed)
title: ~/Project/MusicEd


#
# CONTENT SETTINGS
#
date_format: '%B %d, %Y'
tag_layout: tag.html
tags_url: /tag/

# Containers.
containers:
    projects:
        sort: name
        url: /code/<slug>/
